-- Full schema (fresh project). If you already ran the earlier version
-- without is_complete, use migration_add_complete.sql instead.

create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table todos enable row level security;

create policy "Public can read todos" on todos for select using (true);
create policy "Public can insert todos" on todos for insert with check (true);
create policy "Public can update todos" on todos for update using (true) with check (true);
create policy "Public can delete todos" on todos for delete using (true);
